// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/proto/webSocketMsg.proto

package com.example.mrproduct.proto;

public final class WebSocketInfo {
  private WebSocketInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface msgMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:msgMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *1-登录 2-指令消息 3-经纬度消息 4-其他消息 5-退出
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return The type.
     */
    java.lang.String getType();
    /**
     * <pre>
     *1-登录 2-指令消息 3-经纬度消息 4-其他消息 5-退出
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <pre>
     *信息发送者(那个页面发送的)
     * </pre>
     *
     * <code>string user = 2;</code>
     * @return The user.
     */
    java.lang.String getUser();
    /**
     * <pre>
     *信息发送者(那个页面发送的)
     * </pre>
     *
     * <code>string user = 2;</code>
     * @return The bytes for user.
     */
    com.google.protobuf.ByteString
        getUserBytes();

    /**
     * <pre>
     *发送的数据
     * </pre>
     *
     * <code>string message = 3;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <pre>
     *发送的数据
     * </pre>
     *
     * <code>string message = 3;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <pre>
     *其他数据1
     * </pre>
     *
     * <code>string otherMsg = 4;</code>
     * @return The otherMsg.
     */
    java.lang.String getOtherMsg();
    /**
     * <pre>
     *其他数据1
     * </pre>
     *
     * <code>string otherMsg = 4;</code>
     * @return The bytes for otherMsg.
     */
    com.google.protobuf.ByteString
        getOtherMsgBytes();

    /**
     * <pre>
     *其他信息2
     * </pre>
     *
     * <code>bytes otherMsgByte = 5;</code>
     * @return The otherMsgByte.
     */
    com.google.protobuf.ByteString getOtherMsgByte();
  }
  /**
   * Protobuf type {@code msgMessage}
   */
  public static final class msgMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:msgMessage)
      msgMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use msgMessage.newBuilder() to construct.
    private msgMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private msgMessage() {
      type_ = "";
      user_ = "";
      message_ = "";
      otherMsg_ = "";
      otherMsgByte_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new msgMessage();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.mrproduct.proto.WebSocketInfo.internal_static_msgMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.mrproduct.proto.WebSocketInfo.internal_static_msgMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.mrproduct.proto.WebSocketInfo.msgMessage.class, com.example.mrproduct.proto.WebSocketInfo.msgMessage.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object type_ = "";
    /**
     * <pre>
     *1-登录 2-指令消息 3-经纬度消息 4-其他消息 5-退出
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *1-登录 2-指令消息 3-经纬度消息 4-其他消息 5-退出
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object user_ = "";
    /**
     * <pre>
     *信息发送者(那个页面发送的)
     * </pre>
     *
     * <code>string user = 2;</code>
     * @return The user.
     */
    @java.lang.Override
    public java.lang.String getUser() {
      java.lang.Object ref = user_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        user_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *信息发送者(那个页面发送的)
     * </pre>
     *
     * <code>string user = 2;</code>
     * @return The bytes for user.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserBytes() {
      java.lang.Object ref = user_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        user_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object message_ = "";
    /**
     * <pre>
     *发送的数据
     * </pre>
     *
     * <code>string message = 3;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *发送的数据
     * </pre>
     *
     * <code>string message = 3;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OTHERMSG_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object otherMsg_ = "";
    /**
     * <pre>
     *其他数据1
     * </pre>
     *
     * <code>string otherMsg = 4;</code>
     * @return The otherMsg.
     */
    @java.lang.Override
    public java.lang.String getOtherMsg() {
      java.lang.Object ref = otherMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        otherMsg_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *其他数据1
     * </pre>
     *
     * <code>string otherMsg = 4;</code>
     * @return The bytes for otherMsg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOtherMsgBytes() {
      java.lang.Object ref = otherMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        otherMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OTHERMSGBYTE_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString otherMsgByte_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     *其他信息2
     * </pre>
     *
     * <code>bytes otherMsgByte = 5;</code>
     * @return The otherMsgByte.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getOtherMsgByte() {
      return otherMsgByte_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(user_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, user_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, message_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(otherMsg_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, otherMsg_);
      }
      if (!otherMsgByte_.isEmpty()) {
        output.writeBytes(5, otherMsgByte_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(user_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, user_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, message_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(otherMsg_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, otherMsg_);
      }
      if (!otherMsgByte_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, otherMsgByte_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.mrproduct.proto.WebSocketInfo.msgMessage)) {
        return super.equals(obj);
      }
      com.example.mrproduct.proto.WebSocketInfo.msgMessage other = (com.example.mrproduct.proto.WebSocketInfo.msgMessage) obj;

      if (!getType()
          .equals(other.getType())) return false;
      if (!getUser()
          .equals(other.getUser())) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!getOtherMsg()
          .equals(other.getOtherMsg())) return false;
      if (!getOtherMsgByte()
          .equals(other.getOtherMsgByte())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + USER_FIELD_NUMBER;
      hash = (53 * hash) + getUser().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + OTHERMSG_FIELD_NUMBER;
      hash = (53 * hash) + getOtherMsg().hashCode();
      hash = (37 * hash) + OTHERMSGBYTE_FIELD_NUMBER;
      hash = (53 * hash) + getOtherMsgByte().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.mrproduct.proto.WebSocketInfo.msgMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.mrproduct.proto.WebSocketInfo.msgMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.mrproduct.proto.WebSocketInfo.msgMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.mrproduct.proto.WebSocketInfo.msgMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.mrproduct.proto.WebSocketInfo.msgMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.mrproduct.proto.WebSocketInfo.msgMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.mrproduct.proto.WebSocketInfo.msgMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.mrproduct.proto.WebSocketInfo.msgMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.mrproduct.proto.WebSocketInfo.msgMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.mrproduct.proto.WebSocketInfo.msgMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.mrproduct.proto.WebSocketInfo.msgMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.mrproduct.proto.WebSocketInfo.msgMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.mrproduct.proto.WebSocketInfo.msgMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code msgMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:msgMessage)
        com.example.mrproduct.proto.WebSocketInfo.msgMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.mrproduct.proto.WebSocketInfo.internal_static_msgMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.mrproduct.proto.WebSocketInfo.internal_static_msgMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.mrproduct.proto.WebSocketInfo.msgMessage.class, com.example.mrproduct.proto.WebSocketInfo.msgMessage.Builder.class);
      }

      // Construct using com.example.mrproduct.proto.WebSocketInfo.msgMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        type_ = "";
        user_ = "";
        message_ = "";
        otherMsg_ = "";
        otherMsgByte_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.mrproduct.proto.WebSocketInfo.internal_static_msgMessage_descriptor;
      }

      @java.lang.Override
      public com.example.mrproduct.proto.WebSocketInfo.msgMessage getDefaultInstanceForType() {
        return com.example.mrproduct.proto.WebSocketInfo.msgMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.mrproduct.proto.WebSocketInfo.msgMessage build() {
        com.example.mrproduct.proto.WebSocketInfo.msgMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.mrproduct.proto.WebSocketInfo.msgMessage buildPartial() {
        com.example.mrproduct.proto.WebSocketInfo.msgMessage result = new com.example.mrproduct.proto.WebSocketInfo.msgMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.mrproduct.proto.WebSocketInfo.msgMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.type_ = type_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.user_ = user_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.message_ = message_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.otherMsg_ = otherMsg_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.otherMsgByte_ = otherMsgByte_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.mrproduct.proto.WebSocketInfo.msgMessage) {
          return mergeFrom((com.example.mrproduct.proto.WebSocketInfo.msgMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.mrproduct.proto.WebSocketInfo.msgMessage other) {
        if (other == com.example.mrproduct.proto.WebSocketInfo.msgMessage.getDefaultInstance()) return this;
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getUser().isEmpty()) {
          user_ = other.user_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getOtherMsg().isEmpty()) {
          otherMsg_ = other.otherMsg_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.getOtherMsgByte() != com.google.protobuf.ByteString.EMPTY) {
          setOtherMsgByte(other.getOtherMsgByte());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                type_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                user_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                message_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                otherMsg_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                otherMsgByte_ = input.readBytes();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object type_ = "";
      /**
       * <pre>
       *1-登录 2-指令消息 3-经纬度消息 4-其他消息 5-退出
       * </pre>
       *
       * <code>string type = 1;</code>
       * @return The type.
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *1-登录 2-指令消息 3-经纬度消息 4-其他消息 5-退出
       * </pre>
       *
       * <code>string type = 1;</code>
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *1-登录 2-指令消息 3-经纬度消息 4-其他消息 5-退出
       * </pre>
       *
       * <code>string type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        type_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *1-登录 2-指令消息 3-经纬度消息 4-其他消息 5-退出
       * </pre>
       *
       * <code>string type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        type_ = getDefaultInstance().getType();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *1-登录 2-指令消息 3-经纬度消息 4-其他消息 5-退出
       * </pre>
       *
       * <code>string type = 1;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        type_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object user_ = "";
      /**
       * <pre>
       *信息发送者(那个页面发送的)
       * </pre>
       *
       * <code>string user = 2;</code>
       * @return The user.
       */
      public java.lang.String getUser() {
        java.lang.Object ref = user_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          user_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *信息发送者(那个页面发送的)
       * </pre>
       *
       * <code>string user = 2;</code>
       * @return The bytes for user.
       */
      public com.google.protobuf.ByteString
          getUserBytes() {
        java.lang.Object ref = user_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          user_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *信息发送者(那个页面发送的)
       * </pre>
       *
       * <code>string user = 2;</code>
       * @param value The user to set.
       * @return This builder for chaining.
       */
      public Builder setUser(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        user_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *信息发送者(那个页面发送的)
       * </pre>
       *
       * <code>string user = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUser() {
        user_ = getDefaultInstance().getUser();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *信息发送者(那个页面发送的)
       * </pre>
       *
       * <code>string user = 2;</code>
       * @param value The bytes for user to set.
       * @return This builder for chaining.
       */
      public Builder setUserBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        user_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <pre>
       *发送的数据
       * </pre>
       *
       * <code>string message = 3;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *发送的数据
       * </pre>
       *
       * <code>string message = 3;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *发送的数据
       * </pre>
       *
       * <code>string message = 3;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        message_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送的数据
       * </pre>
       *
       * <code>string message = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        message_ = getDefaultInstance().getMessage();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送的数据
       * </pre>
       *
       * <code>string message = 3;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        message_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object otherMsg_ = "";
      /**
       * <pre>
       *其他数据1
       * </pre>
       *
       * <code>string otherMsg = 4;</code>
       * @return The otherMsg.
       */
      public java.lang.String getOtherMsg() {
        java.lang.Object ref = otherMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          otherMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *其他数据1
       * </pre>
       *
       * <code>string otherMsg = 4;</code>
       * @return The bytes for otherMsg.
       */
      public com.google.protobuf.ByteString
          getOtherMsgBytes() {
        java.lang.Object ref = otherMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          otherMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *其他数据1
       * </pre>
       *
       * <code>string otherMsg = 4;</code>
       * @param value The otherMsg to set.
       * @return This builder for chaining.
       */
      public Builder setOtherMsg(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        otherMsg_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *其他数据1
       * </pre>
       *
       * <code>string otherMsg = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearOtherMsg() {
        otherMsg_ = getDefaultInstance().getOtherMsg();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *其他数据1
       * </pre>
       *
       * <code>string otherMsg = 4;</code>
       * @param value The bytes for otherMsg to set.
       * @return This builder for chaining.
       */
      public Builder setOtherMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        otherMsg_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString otherMsgByte_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *其他信息2
       * </pre>
       *
       * <code>bytes otherMsgByte = 5;</code>
       * @return The otherMsgByte.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getOtherMsgByte() {
        return otherMsgByte_;
      }
      /**
       * <pre>
       *其他信息2
       * </pre>
       *
       * <code>bytes otherMsgByte = 5;</code>
       * @param value The otherMsgByte to set.
       * @return This builder for chaining.
       */
      public Builder setOtherMsgByte(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        otherMsgByte_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *其他信息2
       * </pre>
       *
       * <code>bytes otherMsgByte = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearOtherMsgByte() {
        bitField0_ = (bitField0_ & ~0x00000010);
        otherMsgByte_ = getDefaultInstance().getOtherMsgByte();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:msgMessage)
    }

    // @@protoc_insertion_point(class_scope:msgMessage)
    private static final com.example.mrproduct.proto.WebSocketInfo.msgMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.mrproduct.proto.WebSocketInfo.msgMessage();
    }

    public static com.example.mrproduct.proto.WebSocketInfo.msgMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<msgMessage>
        PARSER = new com.google.protobuf.AbstractParser<msgMessage>() {
      @java.lang.Override
      public msgMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<msgMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<msgMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.mrproduct.proto.WebSocketInfo.msgMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msgMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_msgMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034src/proto/webSocketMsg.proto\"a\n\nmsgMes" +
      "sage\022\014\n\004type\030\001 \001(\t\022\014\n\004user\030\002 \001(\t\022\017\n\007mess" +
      "age\030\003 \001(\t\022\020\n\010otherMsg\030\004 \001(\t\022\024\n\014otherMsgB" +
      "yte\030\005 \001(\014B,\n\033com.example.mrproduct.proto" +
      "B\rWebSocketInfob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_msgMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_msgMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_msgMessage_descriptor,
        new java.lang.String[] { "Type", "User", "Message", "OtherMsg", "OtherMsgByte", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
